### ISSUE TITLE
Can't replicate WordPress permalinks

### ISSUE THREAD

**Issue by WheresAlice** [bradlug/bradlug.github.io#10]
So I think we've hit a blocker.  Jekyll can't replicate the permalinks that WordPress has out of the box.  I might be able to come up with something clever, but it's not going to be pretty.

https://jekyllrb.com/docs/permalinks/ documents what you can do with permalinks, whereas WordPress lets you use the full month (February), Jekyll only has month (02), i_month (2) or short_month (Feb).

It's possible we can reproduce all the existing post URLs by overriding the permalink within the posts themselves.  So I'm going to assign this to myself and have a look at that tomorrow, but if any of you have any clever ideas then I'm all ears.

**Comment by xriss** [comment]
Don't think its a problem, 

Can probably work around and worst case it can be fixed by just using custom hosting rather than github with server side URL rewrites to map old URLs only (all that's actually needed is that we do not break old links)

Server side redirects and not using github hosting for anything other than testing is probably best anyhow as it gives more flexibility.

**Comment by NGRhodes** [comment]
The other option is to change the permalink scheme on Wordpress to match what is desired in Jekyl and 301 redirect in htaccess or using a wordpress from old to new scheme.

**Comment by adamhepton** [comment]
Forgive me for intruding and also if I've got the wrong end of the stick: is this useful at all?

https://help.github.com/articles/redirects-on-github-pages/

**Comment by WheresAlice** [comment]
That looks perfect @adamhepton , I shall have a go with that this evening.

**Comment by WheresAlice** [comment]
Yep, works perfectly on a dev branch - thanks @adamhepton .

But it relies on #9 being merged into master before I can go much further with this, and will need to liaise with @caprenter on #1 to make sure we can bring in the redirects.
