### ISSUE TITLE
Landing page introduction

### ISSUE THREAD

**Issue by notshi** [bradlug/bradlug.github.io#26]
The landing page on the site deserves better introduction copy than repeating the same headline; ie. 'A self-help group for GNU/Linux, Open Source and Free Software users in and around the Bradford District, West Yorkshire'

Could we come up with something more descriptive?

Or should we summarise bits from the verbose [meetings](http://bradlug.co.uk/meetings/) page?

**Comment by john-hudson** [comment]
OK Write it. There are various bits of the site which still need tidying up. So any help in making it a better site is very welcome. @WheresAlice @caprenter

**Comment by notshi** [comment]
Done. Pls to be improving :}

**Comment by notshi** [comment]
Spruced up the Meetings page with photos and google map.
