### ISSUE TITLE
Overall site fixes

### ISSUE THREAD

**Issue by notshi** [bradlug/bradlug.github.io#27]
Have done a few things:

- Overall layout css fixes (font sizes, paddings of wrappers and posts for breathing space/legibility)
- Added a 'Meetings' link
- Changed link buttons css
- Added the google calendar to the landing page, just a simple embed so you can see upcoming meetings at a glance
- Made some changes to the landing page (bigger penguin image, etc.)
- Fixed un/ordered lists where text were in paragraphs (old posts with lists should now look better)
- Changed 'circle' icon of lists to 'discs'
- Moved 'Time to read' next to the date
- Fixed blog post 'by author'
- Updated About and Meetings page
- Used post excerpts instead of showing the entire post on the landing page (read time now makes sense!) 
- Removed the rather verbose post.date of blog posts on the landing page but kept it in the individual blog post
- Added 'back to top' link at bottom of pages
- Added second pagination block for when you are at the bottom of the page

There are still a few pages unlinked from the landing page that need sprucing up and linked pages that don't exist.

[Social Meetings](http://bradlug.co.uk/social-meetings/)  - does this still happen?
[FOSS](http://bradlug.co.uk/foss/)  - linked from About page

Links below are linked from [Meetings](http://bradlug.co.uk/meetings/)
[Contact](http://bradlug.co.uk/contact/)  
[Past Meetings](http://bradlug.co.uk/category/past_meetings) - doesn't exist (removed for now)

As always, any of the above can be changed - just state why :}

**Comment by notshi** [comment]
**Questions**

1. Should we link these pages on the landing page navigation bar?
2. Should we add the 'Contact' page link under the 'Ways to get in touch' along with the map?
3. Leave things as they are.

**Comment by notshi** [comment]
@WheresAlice - there seems to be 'categories' label to each blog post [eg.](https://github.com/bradlug/bradlug.github.io/blob/master/_posts/2017-08-05-july-10-2017-appimage-slackbuilds-starplot-meet.markdown)

Can we link [Past Meetings](http://bradlug.co.uk/category/past_meetings) to somewhere?

**Comment by WheresAlice** [comment]
The way we handle categories on the https://github.com/skybet/skybet.github.io site is by having a categories folder in the root of the repo.  In that directory you then need a markdown file for each category.  And finally a layout which renders all the posts in the given category.  There's also a _data file with all of the categories so that you can get a list.

It's probably easier if I raise a pull request which does this.

**Comment by notshi** [comment]
Thanks, @WheresAlice. Will merge.

**Comment by notshi** [comment]
Updates:

- Have linked the category for past-meetings back to the Meetings page
- Mobile view should be fixed now! (plscheckthnx)
- Long urls are now fixed so they don't break the layout

<o/
